<template>
    <div>
        <v-text-field 
        :rules="Rules"
        label="ลำดับที่"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="ชื่อ"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="สกุล"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="วันที่ขอรับการประเมิน"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="วันทีมติกรรมการประจำคณะ"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="วันที่เริ่มประเมิน"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="วันที่ครบกำหนดประเมิน"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="ตำแหน่งที่ขอรับการพิจารณา"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="ระดับผลการประเมินเอกสาร"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="สถานะดำเนินการ"
        ></v-text-field>
    </div>
</template>