<template>
    <div>
        <v-text-field 
        :rules="Rules"
        label="ชื่อ"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="นามสกุล"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="ชื่อเรื่อง"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="สังกัดสาขาวิชา"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="วันที่รับประเมิน"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="วันที่ประเมิน"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="วันที่หมดอายุประเมิน"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="ระดับผลการประเมินการสอน"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="ระดับผลประเมินเอกสาร"
        ></v-text-field>
        <v-text-field 
        :rules="Rules"
        label="ประเมินครั้งที่"
        ></v-text-field>
    </div>
</template>